version: '3.10'

services:
  app:
    volumes:
      - .:/app
    env_file:
      - .env
    build:
      context: .
    expose:
      - 8000

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static: